### ISSUE TITLE
Character can not run "South East"

### ISSUE THREAD

**Issue by Master-Foo** [Master-Foo/game#1]
Running "South East" does not work.

`Shift+LeftArrow+ArrowDown` or `Shift+DownArrow+RightArrow`

However, walking "South East" works just fine.

`LeftArrow+ArrowDown` or `DownArrow+RightArrow`

I'm not sure why. Discuss.

**Comment by jrslagle** [comment]
Neither I nor @techwolf could replicate this bug. Maybe we should add a check for a dependency minimum version number.

**Comment by Master-Foo** [comment]
I think this is an idiosyncrasy with my specific machine / keyboard. If you can't replicate, don't worry about it I'll do some further testing when I have time.

**Comment by Master-Foo** [comment]
I just did a quick sanity check. When I plug a USB keyboard into my laptop, I can run south east normally. Which leads me to believe this is a hardware issue.
