### ISSUE TITLE
If an "animation" has only 1 frame, don't animate it.

### ISSUE THREAD

**Issue by Master-Foo** [Master-Foo/game#10]
As it is, all objects are animated even if there is only 1 frame in the animation. This is because I was lazy when implementing it and getting something to work was more important than making it efficient.

So, for instance, each Tile is looping though an animation despite the fact that this is rather stupid. It wastes resources. It's probably one of the reasons loading takes so long when creating a whole 10,000 hectare of tiles.

Anyway, the animation_config file should stay the same. We just need to make the code that reads the config to be smart enough to recognize that if there is only 1 frame it should not make an Animation object, but just a normal sprite to render.

**Comment by jrslagle** [comment]
Kk. I was hoping to have animated ground tiles like the effects of wind.

But I like the idea of if 1 frame, then paint, else animate.

**Comment by Master-Foo** [comment]
If we want animation for wind, we can just add additional frames to that animation. But, the fact stands. If an animation only has 1 frame, then there is no sense in animating it and incurring the wrath of additional overhead.

**Comment by Master-Foo** [comment]
Fixed. There is a noticeable difference in refresh rate now.
