### ISSUE TITLE
Add tags

### ISSUE THREAD

**Issue by jrslagle** [Master-Foo/game#16]
I can't seem to add tags to issues, so maybe @Master-Foo you have to do it. I was hoping for at least a tag called "Ready to implement" as in an issue with no prerequisites. Having a mind map where we can see what becomes Ready after one issue is solved would be great. But the best I can think of is putting a note in the issue referencing which issue would become ready next - a terrible solution, but...

**Comment by Master-Foo** [comment]
I think a "Has Prerequisites" tag is better, because the default state of an issue is that it should have no prerequisites, but when we determine that it has prerequisites we add that tag when needed.

**Comment by Master-Foo** [comment]
I've added @jrslagle @techwulf & @deathStarUtah as collaborators on this project. You might be able to add Labels to a project now. Try adding a "Has Prerequisites" Label. If you can't do it tell me and I'll do it myself.

**Comment by jrslagle** [comment]
Yea, I still can't add labels or Assignees. It says you're the owner @Master-Foo , but I don't have a title.

**Comment by jrslagle** [comment]
Off topic. I'm pretty much out of the house from dawn til dusk Monday through Wednesday. I probably won't be able to return much code until Thursday evening at the earliest. Things should clear up a bit in two weeks after school is over.

**Comment by jrslagle** [comment]
I successfully rebased with your code, merged, committed and pushed to my fork. 

Nice rock.
