### ISSUE TITLE
Tile rendering glitch

### ISSUE THREAD

**Issue by Master-Foo** [Master-Foo/game#18]
When walking around a Hectare, there is a strange rendering glitch which leaves a 1 pixel space between tiles allowing the background to show through the tile at it's border.

I suspect this is some kind of floating point error. But I haven't had time to explore.

Someone confirm if they get the same thing on their hardware.

**Comment by jrslagle** [comment]
I get the same glitch. It's between the first and second row. Sometimes between the first and second column too.

**Comment by jrslagle** [comment]
I stopped getting this glitch. Don't know why...

**Comment by Master-Foo** [comment]
This is very low priority. Don't bother with it unless you REALLY feel compelled. It will likely be scrapped when we remove the scaffold.

**Comment by fishscene** [comment]
I don't recall seeing this issue. Probably not worth our time tracking down unless we see this again. Fine with me if we close, but let's double check with the original poster.

**Comment by Master-Foo** [comment]
This stopped happening on my machine. I suspect it was fixed when I updated the tiles so they don't animate.
