### ISSUE TITLE
Streamline Keyboard Listening

### ISSUE THREAD

**Issue by jrslagle** [Master-Foo/game#25]
I've been working on this for just over a day now. At first I was just bugged that source/interface/keyboard.py lists each key three times. This makes it easy to miss one if you're adding to the framework, and it's unnecessarily verbose.

Then I got advice on whether to move things around so that the keyboard controller commands the avatar (or menu screens).

Then I talked to another guy about different design architectures, the Law of Demeter, and event handling systems. I read this and decided to implement it
https://en.wikipedia.org/wiki/Observer_pattern
It's a common event handling architecture in games and MVC.

Basically there are reporters which send out event notifications to a list of subscribers. Each subscriber (like the avatar) gets the ID of the key pressed, and then decides whether that means turn left or right. One beautiful thing about the Observer Pattern is it's trivial to add more subscribers which will all get the event stream. So buildings that are clicked, tiles that are selected, buttons that are pressed.

I put the example code from the article in our game, and it's working! I'm printing all the events that stream through as I hit keys and move the mouse - from the avatar controller!

Now I just need to extract the event data, and have that modify the avatar's state when a key is pressed. Then decouple and clean up any dead code. Hopefully this will clean up some of the CPU load, since resetting the move state can be done per event rather than per frame.

A further step would be subscribers submit the events they care about when they subscribe. Those subscriptions are registered into a hash of a list of subscribers per subscribed key. When that key is pressed, the hash is used to get that list of subscribers, and then only those subscribers receive the events they care about. Also that key hash only contains keys that are subscribed to.

**Comment by Master-Foo** [comment]
Actually, this is something I have been knawing on in the back of my mind for a while (The list in my head is 100x that of the issues posted in this project.)

@jrslagle is correct. This is the "better" way to do it. It shouldn't require too much modification.

I just haven't gotten around to it yet. You might run into issues, for instance, what if you want to register both the up key and right key to move NW? It might work with the observer pattern, it might not. I haven't tried it yet, so, it's a hypothetical barrier.

**Comment by Master-Foo** [comment]
While you are poking around the keyboard stuff... You might as well take care of issue: Expand source.interface.keyboard #11

**Comment by jrslagle** [comment]
The improvement I was thinking that negates #11 is, each subscriber submits the event types they want to be notified of. The reporter keeps a dictionary like 

{
UP_K : [Avatar], 
DOWN_K : [Avatar], 
F5_K : [SaveGame], 
L_CLICK : [Avatar, Hectare] 
} 

If an event key isn't represented, ignore it. If it's present, notify that list of subscribers. When a new subscriber subscribes, the reporter adds their keys to this dictionary.

**Comment by Master-Foo** [comment]
Not so much that way.

What should happen is, the observer's controller (for instance Avatar Controller) should have a function like this:

``` python
def on_K_up(self):
    #Respond to key event
    pass
```

the observable (Keyboard) should determine which key is being pressed and then do something like this

``` python
for observer in self.observers:
    observer.on_K_up()
pass
```

**Comment by Master-Foo** [comment]
I finished this.

**Comment by jrslagle** [comment]
God dam!

**Comment by Master-Foo** [comment]
Be glad you only peeked into that rabbit hole.

Here, I'm assigning issue: Expand source.interface.keyboard #11 since it's starting to become a priority. 

I almost have the framework to the point where we can start punching out game play features in rapid succession and I don't want problems like "That key isn't mapped" to be something that slows us down. If someone is making a feature and they need the `<` key they should just be able to use it.
