### ISSUE TITLE
Create a Potato

### ISSUE THREAD

**Issue by Master-Foo** [Master-Foo/game#27]
I made a Corn Entity it grows over the course of about a minute. Look at that and create a new entity for a potato. The images ready exist.

Pro tip: This is really super stupid and simple. Don't do anything fancy. Don't submit anything that doesn't have anything to do with the potato. Start a new project clone without all the garbage. make a branch called "potato"

``` bash
git branch potato
```

make a potato

then submit that for review. Don't submit ANYTHING ELSE except for a couple of files pertaining to the damn potato. No .idea folders, no code you copied from someone else, no code from other issues you are working on. JUST the code from your potato branch.

You'll probably be able to have this done and submitted and approved in 1 hour's worth of work.

**Comment by jrslagle** [comment]
As I understand it, my work stack is: keyboard observer pattern (#25), then PR #21, then animations (#2), then this. Should I rearrange that order or remove things? 

While I'm done with finals and Done Club, I have an obnoxious amount of Christmas prep to do this week, including prepping my car for a drive to Sacramento. I'm not out of the woods yet. Next week starting Monday looks much better.

**Comment by Master-Foo** [comment]
I gave you specifically this project because it is something you can do in a short amount of time. You'll get SOMETHING into the commit history. Which, BTW, you still have a pending code review from your last pull request. So, THAT if anything should be your priority. Not keyboard stuff, not PR, not animations.

Finish what you've already started, which is your last pull request. Then do this Potato, because it will take you 1 hour if you don't over think it. Then move on to whatever else is in your pipeline.

There is a reason your name doesn't appear on [this page](https://github.com/Master-Foo/game/commits/master). How many hours have you spent so far? You should have SOMETHING. For the time being, just do really fucking simple and stupid tasks. You'll get some code submitted, and then, when you have some inertia, you can move on to the more heavy concepts, like the keyboard and animation stuff.
