### ISSUE TITLE
Make Electronic an Abstract Class

### ISSUE THREAD

**Issue by Master-Foo** [Master-Foo/game#52]
Electronics inherit from inanimate. There should be a Electronic class which all Electronics inherit from. Likewise, Electronic should inherit from inanimate.

Move shared code from Battery, SolarPannel, Refinery, ect, into Electronic.

**Comment by fishscene** [comment]
The file:
source/abstract/entities/inanimate/electronic/animation_config/stand.py 

This file has: 
`"entity_name" : "avatar",`
Should it be?:
`"entity_name" : "electronic",`

I was attempting a shot at https://github.com/Master-Foo/game/issues/51 by replicating the changes made here, but for plants and ran across this. I also noticed when running the game the Avatar either stands still or walks in place - but cannot move around on the map at all. Always stuck facing North.

I wasn't sure if this was the cause of that bug or not. I ran out of time to test as I'm off to see a movie. :)

**Comment by Master-Foo** [comment]
Ideally, there should be a "generic" graphic for all electronic objects that we can use to display it. Even if there is no graphic for, say, a toaster, at least we have a fall-back graphic.

I'm not too concerned that the "default" is the same as the avatar because displaying the avatar is better than nothing. But if someone wants to take the time to make a generic electronic graphic, that's fine. Just don't spend a lot of time on it.

The graphics we are using right now are for testing purposes only, so we don't **need** to spend a great deal of time to get it correct. As long as we have **something** to display and interact with.

If we **do** spend time on graphics, it should be on modeling 3D assets that we will use in the future.

As for the avatar that is always facing north, you might be confusing that with the NPC which I made as a place holder for future development. Avarar and NPC both inherit from human. But Avatar is controlled by the player and NPC will be controlled by AI. (AI isn't written yet, that's the "future development" I was speaking of)

If anyone wants to create a separate graphic for NPC so it's not confused with the Avatar, go for it. Create a new Issue for it and assign yourself. The Avatar is from the game "Chrono Trigger" you can probably find graphics for other characters from that game and replace those images with the current NPC images fairly easily. But, I don't personally find it a priority. I think we can all work on more important things than graphics which we won't be using when we convert to a 3D engine.

**Comment by jrslagle** [comment]
I figured out why the refinery and such wouldn't render when their view objects imported from electronic.view. It was because electronic.view had an empty on_render() method that was overriding entity.view.on_render().

Works now!

**Comment by Master-Foo** [comment]
Cool. BTW. I'm in the process of removing the `ElementalStorageUnit` from the game. Basically, it just serves as a book-keeping device which should be handled by `Logistics` and it doesn't really need to be an `Entity`. `Logistics` will now have the functionality of the `ESU`. Otherwise, everything works the same. We just don't need to worry about the `ESU`.

Also, I'm mulling around the idea of consolidating the `ElementalStorageTank` So, instead of having 90+ Elemental storage tanks that each hold their own element, you'd have one large tank that can hold multiple kinds of elements.

So, if you have a tank with a capacity of 100, you can store 100 Hydrogen, or 100 Oxygen, or 50 H and 50 O, etc.

You can still have multiple tanks, it's just that the tanks are generic in functionality. I think this will eliminate some unnecessary complexity from the game.
