### ISSUE TITLE
Requirements to run have changed

### ISSUE THREAD

**Issue by fishscene** [Master-Foo/game#57]
Seems like the requirements to run the game have changed. Here's what I've been able to determine is needed to run the game:

```
Ubuntu Linux: 
sudo apt-get install python-tk
sudo -H pip install pygame numpy matplotlib opensimplex sklearn scipy


Windows:
http://sourceforge.net/projects/scipy/files/scipy/0.16.1/scipy-0.16.1-win32-superpack-python2.7.exe/download
pip install pygame numpy matplotlib opensimplex sklearn
```

What OS's are you guys running? I'll see if I can get a couple of VM's and every so often, check the requirements needed to run the game and update the front-page. I'm not really a programmer/coder, but this seems like something I can do.
If I don't hear back in a couple of days, I'll throw a PR with the info I have.

**Comment by Master-Foo** [comment]
That is probably a result of my commit last night for the Solid Noise package. (It's cool check it out). There is a ./requirements.txt file in root which **should** (but probably doesn't) have all the required python libraries inside of it. If anything is missing, add it to the file.

I try to add libraries to the ./requirements.txt when I become aware of them, but a lot of these libraries are already installed on my machine and I don't think about it unless it becomes apparent and I need to actually install them.

Requirements can be installed as such:
```bash
$ sudo pip install -r ./requirements.txt
```

If you are using Windows, that's fine. I'll make fun of you, but I'll admit, it's probably good to have someone who can make sure it is cross platform compatible. I just can't give much advice to anyone using anything other than Linux.

If you want to be the guy in charge of Windows compatibility, go for it.

**Comment by fishscene** [comment]
No worries. I classify myself as a "Linux enthusiast" and am most familiar with Ubuntu.
I have no problem tracking requirements to get the game running on different platforms, although for some reason, I'm having significant difficulty on my Mac with a possibly borked Python install. (again, after I fixed it with Jimmy)

I ran "sudo pip install -r ./requirements.txt" on Ubuntu 16.10 x64 and there's no "pygame-sdl2". I'm assuming pip may be able to find it on other distro's, so I broke out your handy pip install line to "Generic Linux" and included the Ubuntu-specific version.

**Comment by jrslagle** [comment]
I'm running Arch Linux, and so is @techwulf. We install stuff like
sudo pacman -S vim
pacman is our package manager, and -S is install. That would be cool if you were able to determine requirements. I'm going to take notes as I get the solid noise package working, so I'll let you know.
