### ISSUE TITLE
Add a hold_item action to Avatar

### ISSUE THREAD

**Issue by Master-Foo** [Master-Foo/game#6]
An action for holding items in the game.

This is the first action which allows us to interact with other objects in the game.

Things we need to do to make this happen:

1. Create character graphics for holding an item. (Get issue: Create Character Graphics done first)
2. Add a is_holding state to the model
3. Add animation state to view
4. issue: Make a holdable item #7
4. ??? more discussion

**Comment by jrslagle** [comment]
Can we say this is accomplished?

**Comment by Master-Foo** [comment]
No I'm waiting for @deathStarUtah to finish his [code review](https://github.com/Master-Foo/game/pull/20)

**Comment by deathStarUtah** [comment]
I finished it on sunday.

**Comment by Master-Foo** [comment]
@deathStarUtah, I'll go take a look.

Note to everyone... I don't know if you have finished a code review if I don't get a pull request or a message in the pull request conversation that asks me to take another look. FYI.

**Comment by jrslagle** [comment]
Before we can get #39 up, we need this. So I'm picking through Alex's code and doing it how I want.

@Master-Foo, should the hold action go in animate or human?

**Comment by jrslagle** [comment]
Actually, if your bots can hold things, then animate, definitely in animate.

**Comment by jrslagle** [comment]
This ones actually kind of tricky.... Different aspects of Avatar are implemented at different steps of his inheritance chain, and a lot of it doesn't make sense to me. I've gotta map this out on paper.

**Comment by Master-Foo** [comment]
I'm not entirely sure what you are talking about. So, put it where you think it should go and I'll scold you in code review.

Anyway, the general rule of thumb is.

1. Modifying state usually belongs in the mode.

unless...

2. You are using state to display data, then it goes in the view

3. Code which is dependent on user interaction, or events belongs in the Controller.

4. Sometimes you just have to use your best judgment.

**Comment by jrslagle** [comment]
I meant which levels contain which code - Entity > Animate > Human > Avatar. But same applies, use my best judgment and see what you think. I just have to chart out what is already where because it looks like several aspects are implemented on multiple inheritance levels, like move states. In those cases, the child class shouldn't have the redundant code right?

**Comment by jrslagle** [comment]
But thank you for the MCV explanation. The line between controller and model are often blurry for me.

**Comment by Master-Foo** [comment]
If there is redundant move code, it should probably go into Animate and removed from whatever else it is in (provided it still works. test it and see).

**Comment by Master-Foo** [comment]
Done.
