### ISSUE TITLE
Revamp velocity system.

### ISSUE THREAD

**Issue by Master-Foo** [Master-Foo/game#8]
velocity is a 1D variable, we need to change it to allow for multiple directions. For instance jumping.

Or, add a jump_velocity to the Model.

Discuss...

---

Update:

After thinking about it, here is what we need.

position = Vector3d()
direction = Vector3d()
impulse = Vector3d()
mass = float

the velocity() method will probably have to be scrapped as well. But the idea is, that this is a more realistic method of determining velocity.

**Comment by jrslagle** [comment]
Velocity should be a Vector3 for sure.

**Comment by jrslagle** [comment]
I was thinking about having a special free-fall boolean. When you jump, and add your initial jump velocity vector to your total velocity. While in free fall, walking, running, and other contact-with-ground actions are disabled. Free-fall ends when you collide with anything.

**Comment by jrslagle** [comment]
While in free-fall, your velocity would be updated only by adding the gravity vector3 (3.711 straight down) to your velocity.

**Comment by jrslagle** [comment]
This was posted in issue #5.

The more I think about this, the more I think we'll avoid future bugs by avoiding special move states. Otherwise you'll run into bugs like what happens when multiple actions are happening to you at once. I motion to refactor for a force diagram.

Net force on you is (gravity + normal force + friction). Anything that strikes you just gets appended to a force array and you go flying. 

Thoughts? 

@Master-Foo, I like the variables you've laid out.

**Comment by Master-Foo** [comment]
Take some time to work out the physics. The current system was a hack to get things working. So, don't be afraid to scrap what exists.

**Comment by Master-Foo** [comment]
Also, I'm not sure how up-to-speed you are on vector math. But, if not, dive into it and learn.

**Comment by Master-Foo** [comment]
The Vector3 classes have the methods you should need. Just know how to use them.

**Comment by jrslagle** [comment]
I'm confident with physics, but could use a refresher on dot products and the like.

**Comment by jrslagle** [comment]
Probably unwise to ask before looking, but doesn't pygame have a physics engine we can just import?

**Comment by Master-Foo** [comment]
No, not so much. Physics are usually something imported from a physics engine. For instance, Box2d is a good library for doing collisions.

There is a dirty secret though. Most games don't do a great deal of actual physics simulations because it's expensive and can be faked for much, much cheaper. For instance, the Vector Math takes care of most everything we need right now. To add gravity, all we need to to is calculate the Avatar's vector against a gravitational force vector and BAM we have gravity. Then all we need to do is say "If the Avatar's z position is less than or equal to the tile's z position, the Avatar's z position is the same as the Tile's z position" That is a much cheaper calculation than using a dedicated physic's engine.

**Comment by Master-Foo** [comment]
I finished this.
