### ISSUE TITLE
Add Varied Terrain 

### ISSUE THREAD

**Issue by jrslagle** [Master-Foo/game#9]
This requires a few prerequisites. 

-reorganize code for different kinds of tiles
-pull tile types from a terrain file. 
-allow editing of the terrain file (load, edit, save) 

There is already art for transitions between grass and dirt somewhere in resources that would save you some art time.

**Comment by jrslagle** [comment]
I originally called this "add rock to terrain", but then realized terrain is its own thing. Woopsie!

**Comment by Master-Foo** [comment]
Make a separate issue for each of those prerequisites. We'll discuss them in more detail there. You can link to other issues by putting a hash in front of the issue number. For instance,

Add Varied Terrain #9

links to this issue.

**Comment by jrslagle** [comment]
Done:
#13 
#14 
#15
